# ===================================================================
#             MimicMotion Universal Inference Config
# ===================================================================

# --- Base Model & Checkpoint Paths ---
base_model_path: stabilityai/stable-video-diffusion-img2vid-xt-1-1
ckpt_path: models/MimicMotion_1-1.pth

# ===================================================================
#                        Animation Task
# ===================================================================
test_case:
  -
    # ===============================================================
    #                 THE ONLY TWO LINES YOU NEED TO CHANGE
    # ---------------------------------------------------------------
    # Set to 'false' to generate motion from the video, creating new pose files.
    # Set to 'true' to load motion from the cached pose files.
    use_cached_pose: false

    save_pose_images: true            # turn on/off frame dumps
    pose_images_dir: "C:/MimicMotion/PoseCache/pose_previews"  # relative to output_dir
    
    # Path to the video file that provides the motion.
    # This is used for BOTH generating poses and for naming the cache folder.
    motion_video_path: "G:/My Drive/LIVA/Bucket/Temp/Talking_1280_768.mp4"
    # ===============================================================


    # --- Common Parameters (Always Used) ---talking_2-talking_3

    # Path to the image of the character you want to animate.
    #character_image_path: "G:/My Drive/LIVA/Bucket/Temp/Agent_2/Agent_2_base_img_old_1280_768.png"
    #character_image_path: "G:/My Drive/LIVA/Bucket/Temp/Agent_4/Agent_4_base_img_1280_768.png"
    character_image_path: "G:/My Drive/LIVA/Bucket/Temp/Agent_3/Agent_3_base_img_1280_768.png"

    # Directory where the final pose data (JSONs) will be saved to or loaded from.
    # A subfolder named after the motion video will be created here.
    dw_pose_dir: "C:/MimicMotion/PoseCache"
    
    # The resolution of the output video.
    resolution: 576
    
    # Total number of frames to generate for the final video.
    num_frames: 40
  
    # How many frames to skip in the motion video. 2 means process every 2nd frame.
    sample_stride: 2

    # Animation and generation settings.
    fps: 16
    seed: 100
    num_inference_steps: 25
    guidance_scale: 2.0
    noise_aug_strength: 0
    
    # Settings for handling long videos (tiling).
    frames_overlap: 6